spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bms?characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: localhost
    port: 6379
    password: 123

  cache:
    ehcache:
      config: classpath:config/ehcache.xml

  servlet:
    multipart:
      location: e:/

  resources:
    static-locations: file:${spring.servlet.multipart.location}, classpath:static


#  freemarker:
#    check-template-location: false

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql